services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    platform: linux/amd64  # 明确指定镜像架构为 x86_64
    restart: always
    # 在本地开发，hostname 建议直接设为 localhost 或你的局域网 IP
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # 【关键修改】 external_url 必须和你浏览器输入的地址一致
        # 如果你通过 http://localhost 访问，这里就填 localhost
        external_url 'http://localhost' 
        
        # 强制指定 SSH 端口，这样 GitLab 界面显示的克隆地址才会带上 :22
        gitlab_rails['gitlab_shell_ssh_port'] = 22 
        
        # 针对本地内存优化（可选，如果你的电脑内存很吃紧）
        # prometheus['enable'] = false
        # sidekiq['max_concurrency'] = 10
    ports:
      - '80:80'      # 如果宿主机 80 被占用，可以改成 '8080:80'
      - '443:443'    # HTTPS 访问
      - '22:22'    # SSH 访问
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'